# Generated by Django 5.1 on 2024-08-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='images/photo_2024-08-26_21-00-35.jpg', upload_to='images/'),
        ),
    ]
